apiVersion: v1
kind: Pod
metadata:
  name: test-connection-pod
  namespace: default
  labels:
    purpose: demonstrate-connection
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo The pod has started; sleep 3600']
